#spring.data.mongodb.uri= mongodb+srv://root:pass@cluster0-cqwib.mongodb.net/academic
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: pass
      database: academic
      port: 27017
      host: localhost

  jjwt:
    secret: 4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjW
    expiration: 120

  springreactive:
    username: admin
    pass: root


springdoc:
  swagger-ui:
    path: /swagger-ui.html